### ISSUE TITLE
Login redirect problem

### ISSUE THREAD

**Issue by satouriko** [NEUP-Net-Depart/NEUP-Repair-backend#1]
硬件部反映说那个登录的时候要
1. 扫码打开登录页面
2. 登录（跳转到固定网址）
3. 再扫码查看用户的维修

希望改善跳转逻辑

可能的解决方案，在登录链接/跳转url中加入路由参数`?next=/someuri`或`?continue=/someuri`等，登陆以后自动跳转回原页面

另外不知现在是否可以记住登录，如果可以将是极好的

**Comment by VOID001** [comment]
@hudson6666 其实是可以的，session有保存，只不过QQ里面的浏览器它自己好像对session支持的非常差

**Comment by satouriko** [comment]
@VOID001 应得到解决 大部分扫码都是用微信/QQ，都存在此问题

**Comment by umarufans** [comment]
可以试一下 token (e.g. bearer token) 现在前端很少用 sessionID 做鉴权了。

**Comment by VOID001** [comment]
问题了解了, 有时间的时候我考虑一下如何解决
